name: flpfbonew
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  http: ^0.13.5
  shared_preferences: ^2.0.15
  package_info: ^2.0.2
  flutter_form_builder: ^7.7.0
  flutter_rating_bar: ^4.0.1
  form_builder_validators: ^8.4.0
  progress_dialog: ^1.2.4
  flutter_awesome_alert_box: ^2.1.1
  flutter_typeahead: ^4.1.1
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  sqflite: ^2.2.2
  fluttertoast: ^8.1.2
  flutter_html: ^2.2.1
  get_ip: ^0.4.0
  badges: ^2.0.3
  #flutter_rating_bar: ^3.0.1+1
  flutter_swiper: ^1.1.6
  photo_view: ^0.14.0
  ffi: ^1.1.2
  solid_bottom_sheet: ^0.1.9
  shimmer: ^2.0.0
  flutter_webview_plugin: ^0.4.0
  url_launcher: ^6.1.9
  font_awesome_flutter: ^10.3.0
  firebase_messaging: ^14.1.4
  firebase_core: ^2.4.0
  sms_autofill: ^2.2.0
  firebase_dynamic_links: ^5.0.10
  flutter_local_notifications: ^9.0.1
  multiselect_formfield: ^0.1.4
  datetime_picker_formfield: ^2.0.1
  share: ^2.0.4
  image_picker: ^0.8.6
  date_range_picker: ^1.0.7
  flutter_ip: ^0.2.0

#  paytm: ^3.0.1
  file_picker: ^4.6.1
  device_info: ^2.0.3
  #paytm: ^1.0.8
  get: ^4.6.5
  pull_to_refresh: ^2.0.0
  store_redirect: ^2.0.1
  #geolocation: ^1.1.2
  #permission_handler: ^5.0.1+1
  circular_countdown_timer: ^0.2.3
  in_app_review: ^2.0.6
  dio: ^4.0.6
  path_provider: ^2.0.11
  open_file: ^3.2.1
  ndialog: ^4.1.0
  grouped_list: ^5.1.2
  editable: ^2.0.0
  flutter_slidable: ^0.5.7
  flutter_bloc: ^8.1.3
  syncfusion_flutter_pdfviewer:
  webview_flutter:


dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  country_pickers: ^2.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/Logo/
#    - assets/images/drawers/
#    - assets/images/icons/

#    - assets/BGImages/
#    - assets/DrawerIcons/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue.ttf
        - asset: assets/fonts/HelveticaNeue_Light.ttf
          weight: 500
        - asset: assets/fonts/HelveticaNeue_Medium.ttf
          weight: 600
        - asset: assets/fonts/HelveticaNeue_Thin.ttf
          weight: 400

    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Bold.otf
          weight: 600
        - asset: assets/fonts/Merriweather-Regular.otf
          weight: 500
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 500
    - family: Scriptorama
      fonts:
        - asset: assets/fonts/Scriptorama-Tradeshow-JF-Regular.ttf
          weight: 600
        - asset: assets/fonts/Scriptorama-Tradeshow-JF-Regular.ttf
          weight: 500
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
